artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion #where the data will be downloaded
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip #link where data to be downloaded is present
  local_data_file: artifacts/data_ingestion/data.zip #where the data will be downloaded in zip
  unzip_dir: artifacts/data_ingestion #where the data will be unzipped
